/**
 *
 *  Games.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Games.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::sqlite3;

const std::string Games::Cols::_gameId = "gameId";
const std::string Games::Cols::_stateId = "stateId";
const std::string Games::Cols::_newStateId = "newStateId";
const std::string Games::Cols::_white = "white";
const std::string Games::Cols::_black = "black";
const std::string Games::Cols::_created = "created";
const std::string Games::primaryKeyName = "gameId";
const bool Games::hasPrimaryKey = true;
const std::string Games::tableName = "games";

const std::vector<typename Games::MetaData> Games::metaData_={
{"gameId","uint64_t","integer",8,0,1,0},
{"stateId","uint64_t","integer",8,0,0,1},
{"newStateId","uint64_t","integer",8,0,0,0},
{"white","std::string","varchar",0,0,0,1},
{"black","std::string","varchar",0,0,0,1},
{"created","::trantor::Date","datetime",0,0,0,1}
};
const std::string &Games::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Games::Games(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["gameId"].isNull())
        {
            gameid_=std::make_shared<uint64_t>(r["gameId"].as<uint64_t>());
        }
        if(!r["stateId"].isNull())
        {
            stateid_=std::make_shared<uint64_t>(r["stateId"].as<uint64_t>());
        }
        if(!r["newStateId"].isNull())
        {
            newstateid_=std::make_shared<uint64_t>(r["newStateId"].as<uint64_t>());
        }
        if(!r["white"].isNull())
        {
            white_=std::make_shared<std::string>(r["white"].as<std::string>());
        }
        if(!r["black"].isNull())
        {
            black_=std::make_shared<std::string>(r["black"].as<std::string>());
        }
        if(!r["created"].isNull())
        {
            auto timeStr = r["created"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            gameid_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            stateid_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            newstateid_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            white_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            black_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }

}

Games::Games(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            gameid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            stateid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            newstateid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            white_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            black_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }
}

Games::Games(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("gameId"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["gameId"].isNull())
        {
            gameid_=std::make_shared<uint64_t>((uint64_t)pJson["gameId"].asUInt64());
        }
    }
    if(pJson.isMember("stateId"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["stateId"].isNull())
        {
            stateid_=std::make_shared<uint64_t>((uint64_t)pJson["stateId"].asUInt64());
        }
    }
    if(pJson.isMember("newStateId"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["newStateId"].isNull())
        {
            newstateid_=std::make_shared<uint64_t>((uint64_t)pJson["newStateId"].asUInt64());
        }
    }
    if(pJson.isMember("white"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["white"].isNull())
        {
            white_=std::make_shared<std::string>(pJson["white"].asString());
        }
    }
    if(pJson.isMember("black"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["black"].isNull())
        {
            black_=std::make_shared<std::string>(pJson["black"].asString());
        }
    }
    if(pJson.isMember("created"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["created"].isNull())
        {
            auto timeStr = pJson["created"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }
}

void Games::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            gameid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            stateid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            newstateid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            white_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            black_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }
}
                                                                    
void Games::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("gameId"))
    {
        if(!pJson["gameId"].isNull())
        {
            gameid_=std::make_shared<uint64_t>((uint64_t)pJson["gameId"].asUInt64());
        }
    }
    if(pJson.isMember("stateId"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["stateId"].isNull())
        {
            stateid_=std::make_shared<uint64_t>((uint64_t)pJson["stateId"].asUInt64());
        }
    }
    if(pJson.isMember("newStateId"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["newStateId"].isNull())
        {
            newstateid_=std::make_shared<uint64_t>((uint64_t)pJson["newStateId"].asUInt64());
        }
    }
    if(pJson.isMember("white"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["white"].isNull())
        {
            white_=std::make_shared<std::string>(pJson["white"].asString());
        }
    }
    if(pJson.isMember("black"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["black"].isNull())
        {
            black_=std::make_shared<std::string>(pJson["black"].asString());
        }
    }
    if(pJson.isMember("created"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["created"].isNull())
        {
            auto timeStr = pJson["created"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }
}

const uint64_t &Games::getValueOfGameid() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(gameid_)
        return *gameid_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Games::getGameid() const noexcept
{
    return gameid_;
}
void Games::setGameid(const uint64_t &pGameid) noexcept
{
    gameid_ = std::make_shared<uint64_t>(pGameid);
    dirtyFlag_[0] = true;
}


void Games::setGameidToNull() noexcept
{
    gameid_.reset();
    dirtyFlag_[0] = true;
}

const typename Games::PrimaryKeyType & Games::getPrimaryKey() const
{
    assert(gameid_);
    return *gameid_;
}

const uint64_t &Games::getValueOfStateid() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(stateid_)
        return *stateid_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Games::getStateid() const noexcept
{
    return stateid_;
}
void Games::setStateid(const uint64_t &pStateid) noexcept
{
    stateid_ = std::make_shared<uint64_t>(pStateid);
    dirtyFlag_[1] = true;
}




const uint64_t &Games::getValueOfNewstateid() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(newstateid_)
        return *newstateid_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Games::getNewstateid() const noexcept
{
    return newstateid_;
}
void Games::setNewstateid(const uint64_t &pNewstateid) noexcept
{
    newstateid_ = std::make_shared<uint64_t>(pNewstateid);
    dirtyFlag_[2] = true;
}


void Games::setNewstateidToNull() noexcept
{
    newstateid_.reset();
    dirtyFlag_[2] = true;
}


const std::string &Games::getValueOfWhite() const noexcept
{
    const static std::string defaultValue = std::string();
    if(white_)
        return *white_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Games::getWhite() const noexcept
{
    return white_;
}
void Games::setWhite(const std::string &pWhite) noexcept
{
    white_ = std::make_shared<std::string>(pWhite);
    dirtyFlag_[3] = true;
}
void Games::setWhite(std::string &&pWhite) noexcept
{
    white_ = std::make_shared<std::string>(std::move(pWhite));
    dirtyFlag_[3] = true;
}




const std::string &Games::getValueOfBlack() const noexcept
{
    const static std::string defaultValue = std::string();
    if(black_)
        return *black_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Games::getBlack() const noexcept
{
    return black_;
}
void Games::setBlack(const std::string &pBlack) noexcept
{
    black_ = std::make_shared<std::string>(pBlack);
    dirtyFlag_[4] = true;
}
void Games::setBlack(std::string &&pBlack) noexcept
{
    black_ = std::make_shared<std::string>(std::move(pBlack));
    dirtyFlag_[4] = true;
}




const ::trantor::Date &Games::getValueOfCreated() const noexcept
{
    const static ::trantor::Date defaultValue = ::trantor::Date();
    if(created_)
        return *created_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Games::getCreated() const noexcept
{
    return created_;
}
void Games::setCreated(const ::trantor::Date &pCreated) noexcept
{
    created_ = std::make_shared<::trantor::Date>(pCreated);
    dirtyFlag_[5] = true;
}




void Games::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Games::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "gameId",
        "stateId",
        "newStateId",
        "white",
        "black",
        "created"
    };
    return inCols;
}

void Games::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getGameid())
        {
            binder << getValueOfGameid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStateid())
        {
            binder << getValueOfStateid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNewstateid())
        {
            binder << getValueOfNewstateid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getWhite())
        {
            binder << getValueOfWhite();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getBlack())
        {
            binder << getValueOfBlack();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreated())
        {
            binder << getValueOfCreated();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Games::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Games::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getGameid())
        {
            binder << getValueOfGameid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStateid())
        {
            binder << getValueOfStateid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNewstateid())
        {
            binder << getValueOfNewstateid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getWhite())
        {
            binder << getValueOfWhite();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getBlack())
        {
            binder << getValueOfBlack();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreated())
        {
            binder << getValueOfCreated();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Games::toJson() const
{
    Json::Value ret;
    if(getGameid())
    {
        ret["gameId"]=(Json::UInt64)getValueOfGameid();
    }
    else
    {
        ret["gameId"]=Json::Value();
    }
    if(getStateid())
    {
        ret["stateId"]=(Json::UInt64)getValueOfStateid();
    }
    else
    {
        ret["stateId"]=Json::Value();
    }
    if(getNewstateid())
    {
        ret["newStateId"]=(Json::UInt64)getValueOfNewstateid();
    }
    else
    {
        ret["newStateId"]=Json::Value();
    }
    if(getWhite())
    {
        ret["white"]=getValueOfWhite();
    }
    else
    {
        ret["white"]=Json::Value();
    }
    if(getBlack())
    {
        ret["black"]=getValueOfBlack();
    }
    else
    {
        ret["black"]=Json::Value();
    }
    if(getCreated())
    {
        ret["created"]=getCreated()->toDbStringLocal();
    }
    else
    {
        ret["created"]=Json::Value();
    }
    return ret;
}

Json::Value Games::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getGameid())
            {
                ret[pMasqueradingVector[0]]=(Json::UInt64)getValueOfGameid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getStateid())
            {
                ret[pMasqueradingVector[1]]=(Json::UInt64)getValueOfStateid();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getNewstateid())
            {
                ret[pMasqueradingVector[2]]=(Json::UInt64)getValueOfNewstateid();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getWhite())
            {
                ret[pMasqueradingVector[3]]=getValueOfWhite();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getBlack())
            {
                ret[pMasqueradingVector[4]]=getValueOfBlack();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCreated())
            {
                ret[pMasqueradingVector[5]]=getCreated()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getGameid())
    {
        ret["gameId"]=(Json::UInt64)getValueOfGameid();
    }
    else
    {
        ret["gameId"]=Json::Value();
    }
    if(getStateid())
    {
        ret["stateId"]=(Json::UInt64)getValueOfStateid();
    }
    else
    {
        ret["stateId"]=Json::Value();
    }
    if(getNewstateid())
    {
        ret["newStateId"]=(Json::UInt64)getValueOfNewstateid();
    }
    else
    {
        ret["newStateId"]=Json::Value();
    }
    if(getWhite())
    {
        ret["white"]=getValueOfWhite();
    }
    else
    {
        ret["white"]=Json::Value();
    }
    if(getBlack())
    {
        ret["black"]=getValueOfBlack();
    }
    else
    {
        ret["black"]=Json::Value();
    }
    if(getCreated())
    {
        ret["created"]=getCreated()->toDbStringLocal();
    }
    else
    {
        ret["created"]=Json::Value();
    }
    return ret;
}

bool Games::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("gameId"))
    {
        if(!validJsonOfField(0, "gameId", pJson["gameId"], err, true))
            return false;
    }
    if(pJson.isMember("stateId"))
    {
        if(!validJsonOfField(1, "stateId", pJson["stateId"], err, true))
            return false;
    }
    else
    {
        err="The stateId column cannot be null";
        return false;
    }
    if(pJson.isMember("newStateId"))
    {
        if(!validJsonOfField(2, "newStateId", pJson["newStateId"], err, true))
            return false;
    }
    if(pJson.isMember("white"))
    {
        if(!validJsonOfField(3, "white", pJson["white"], err, true))
            return false;
    }
    else
    {
        err="The white column cannot be null";
        return false;
    }
    if(pJson.isMember("black"))
    {
        if(!validJsonOfField(4, "black", pJson["black"], err, true))
            return false;
    }
    else
    {
        err="The black column cannot be null";
        return false;
    }
    if(pJson.isMember("created"))
    {
        if(!validJsonOfField(5, "created", pJson["created"], err, true))
            return false;
    }
    return true;
}
bool Games::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    if(!pMasqueradingVector[0].empty())
    {
        if(pJson.isMember(pMasqueradingVector[0]))
        {
            if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                return false;
        }
    }
    if(!pMasqueradingVector[1].empty())
    {
        if(pJson.isMember(pMasqueradingVector[1]))
        {
            if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                return false;
        }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
    }
    if(!pMasqueradingVector[2].empty())
    {
        if(pJson.isMember(pMasqueradingVector[2]))
        {
            if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                return false;
        }
    }
    if(!pMasqueradingVector[3].empty())
    {
        if(pJson.isMember(pMasqueradingVector[3]))
        {
            if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                return false;
        }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
    }
    if(!pMasqueradingVector[4].empty())
    {
        if(pJson.isMember(pMasqueradingVector[4]))
        {
            if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                return false;
        }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
    }
    if(!pMasqueradingVector[5].empty())
    {
        if(pJson.isMember(pMasqueradingVector[5]))
        {
            if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                return false;
        }
    }
    return true;
}
bool Games::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("gameId"))
    {
        if(!validJsonOfField(0, "gameId", pJson["gameId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("stateId"))
    {
        if(!validJsonOfField(1, "stateId", pJson["stateId"], err, false))
            return false;
    }
    if(pJson.isMember("newStateId"))
    {
        if(!validJsonOfField(2, "newStateId", pJson["newStateId"], err, false))
            return false;
    }
    if(pJson.isMember("white"))
    {
        if(!validJsonOfField(3, "white", pJson["white"], err, false))
            return false;
    }
    if(pJson.isMember("black"))
    {
        if(!validJsonOfField(4, "black", pJson["black"], err, false))
            return false;
    }
    if(pJson.isMember("created"))
    {
        if(!validJsonOfField(5, "created", pJson["created"], err, false))
            return false;
    }
    return true;
}
bool Games::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
            return false;
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
            return false;
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
            return false;
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
            return false;
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
            return false;
    }
    return true;
}
bool Games::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson, 
                             std::string &err, 
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
