/**
 *
 *  History.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "History.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon_model::sqlite3;

const std::string History::Cols::_gameId = "gameId";
const std::string History::Cols::_stateId = "stateId";
const std::string History::Cols::_prev = "prev";
const std::string History::Cols::_next = "next";
const std::string History::Cols::_created = "created";
const std::string History::primaryKeyName = "gameId";
const bool History::hasPrimaryKey = true;
const std::string History::tableName = "history";

const std::vector<typename History::MetaData> History::metaData_={
{"gameId","uint64_t","integer",8,0,1,1},
{"stateId","uint64_t","integer",8,0,0,1},
{"prev","uint64_t","integer",8,0,0,0},
{"next","uint64_t","integer",8,0,0,0},
{"created","::trantor::Date","datetime",0,0,0,1}
};
const std::string &History::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
History::History(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["gameId"].isNull())
        {
            gameid_=std::make_shared<uint64_t>(r["gameId"].as<uint64_t>());
        }
        if(!r["stateId"].isNull())
        {
            stateid_=std::make_shared<uint64_t>(r["stateId"].as<uint64_t>());
        }
        if(!r["prev"].isNull())
        {
            prev_=std::make_shared<uint64_t>(r["prev"].as<uint64_t>());
        }
        if(!r["next"].isNull())
        {
            next_=std::make_shared<uint64_t>(r["next"].as<uint64_t>());
        }
        if(!r["created"].isNull())
        {
            auto timeStr = r["created"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            gameid_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            stateid_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            prev_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            next_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }

}

History::History(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            gameid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            stateid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            prev_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            next_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }
}

History::History(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("gameId"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["gameId"].isNull())
        {
            gameid_=std::make_shared<uint64_t>((uint64_t)pJson["gameId"].asUInt64());
        }
    }
    if(pJson.isMember("stateId"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["stateId"].isNull())
        {
            stateid_=std::make_shared<uint64_t>((uint64_t)pJson["stateId"].asUInt64());
        }
    }
    if(pJson.isMember("prev"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["prev"].isNull())
        {
            prev_=std::make_shared<uint64_t>((uint64_t)pJson["prev"].asUInt64());
        }
    }
    if(pJson.isMember("next"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["next"].isNull())
        {
            next_=std::make_shared<uint64_t>((uint64_t)pJson["next"].asUInt64());
        }
    }
    if(pJson.isMember("created"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["created"].isNull())
        {
            auto timeStr = pJson["created"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }
}

void History::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            gameid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            stateid_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[1]].asUInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            prev_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[2]].asUInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            next_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[3]].asUInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }
}
                                                                    
void History::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("gameId"))
    {
        if(!pJson["gameId"].isNull())
        {
            gameid_=std::make_shared<uint64_t>((uint64_t)pJson["gameId"].asUInt64());
        }
    }
    if(pJson.isMember("stateId"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["stateId"].isNull())
        {
            stateid_=std::make_shared<uint64_t>((uint64_t)pJson["stateId"].asUInt64());
        }
    }
    if(pJson.isMember("prev"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["prev"].isNull())
        {
            prev_=std::make_shared<uint64_t>((uint64_t)pJson["prev"].asUInt64());
        }
    }
    if(pJson.isMember("next"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["next"].isNull())
        {
            next_=std::make_shared<uint64_t>((uint64_t)pJson["next"].asUInt64());
        }
    }
    if(pJson.isMember("created"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["created"].isNull())
        {
            auto timeStr = pJson["created"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(*p=='.')
            {
                std::string decimals(p+1,&timeStr[timeStr.length()]);
                while(decimals.length()<6)
                {
                    decimals += "0";
                }
                decimalNum = (size_t)atol(decimals.c_str());
            }
            created_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
        }
    }
}

const uint64_t &History::getValueOfGameid() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(gameid_)
        return *gameid_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &History::getGameid() const noexcept
{
    return gameid_;
}
void History::setGameid(const uint64_t &pGameid) noexcept
{
    gameid_ = std::make_shared<uint64_t>(pGameid);
    dirtyFlag_[0] = true;
}



const typename History::PrimaryKeyType & History::getPrimaryKey() const
{
    assert(gameid_);
    return *gameid_;
}

const uint64_t &History::getValueOfStateid() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(stateid_)
        return *stateid_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &History::getStateid() const noexcept
{
    return stateid_;
}
void History::setStateid(const uint64_t &pStateid) noexcept
{
    stateid_ = std::make_shared<uint64_t>(pStateid);
    dirtyFlag_[1] = true;
}




const uint64_t &History::getValueOfPrev() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(prev_)
        return *prev_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &History::getPrev() const noexcept
{
    return prev_;
}
void History::setPrev(const uint64_t &pPrev) noexcept
{
    prev_ = std::make_shared<uint64_t>(pPrev);
    dirtyFlag_[2] = true;
}


void History::setPrevToNull() noexcept
{
    prev_.reset();
    dirtyFlag_[2] = true;
}


const uint64_t &History::getValueOfNext() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(next_)
        return *next_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &History::getNext() const noexcept
{
    return next_;
}
void History::setNext(const uint64_t &pNext) noexcept
{
    next_ = std::make_shared<uint64_t>(pNext);
    dirtyFlag_[3] = true;
}


void History::setNextToNull() noexcept
{
    next_.reset();
    dirtyFlag_[3] = true;
}


const ::trantor::Date &History::getValueOfCreated() const noexcept
{
    const static ::trantor::Date defaultValue = ::trantor::Date();
    if(created_)
        return *created_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &History::getCreated() const noexcept
{
    return created_;
}
void History::setCreated(const ::trantor::Date &pCreated) noexcept
{
    created_ = std::make_shared<::trantor::Date>(pCreated);
    dirtyFlag_[4] = true;
}




void History::updateId(const uint64_t id)
{
}

const std::vector<std::string> &History::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "gameId",
        "stateId",
        "prev",
        "next",
        "created"
    };
    return inCols;
}

void History::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getGameid())
        {
            binder << getValueOfGameid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStateid())
        {
            binder << getValueOfStateid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPrev())
        {
            binder << getValueOfPrev();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getNext())
        {
            binder << getValueOfNext();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCreated())
        {
            binder << getValueOfCreated();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> History::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void History::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getGameid())
        {
            binder << getValueOfGameid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getStateid())
        {
            binder << getValueOfStateid();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPrev())
        {
            binder << getValueOfPrev();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getNext())
        {
            binder << getValueOfNext();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCreated())
        {
            binder << getValueOfCreated();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value History::toJson() const
{
    Json::Value ret;
    if(getGameid())
    {
        ret["gameId"]=(Json::UInt64)getValueOfGameid();
    }
    else
    {
        ret["gameId"]=Json::Value();
    }
    if(getStateid())
    {
        ret["stateId"]=(Json::UInt64)getValueOfStateid();
    }
    else
    {
        ret["stateId"]=Json::Value();
    }
    if(getPrev())
    {
        ret["prev"]=(Json::UInt64)getValueOfPrev();
    }
    else
    {
        ret["prev"]=Json::Value();
    }
    if(getNext())
    {
        ret["next"]=(Json::UInt64)getValueOfNext();
    }
    else
    {
        ret["next"]=Json::Value();
    }
    if(getCreated())
    {
        ret["created"]=getCreated()->toDbStringLocal();
    }
    else
    {
        ret["created"]=Json::Value();
    }
    return ret;
}

Json::Value History::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getGameid())
            {
                ret[pMasqueradingVector[0]]=(Json::UInt64)getValueOfGameid();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getStateid())
            {
                ret[pMasqueradingVector[1]]=(Json::UInt64)getValueOfStateid();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPrev())
            {
                ret[pMasqueradingVector[2]]=(Json::UInt64)getValueOfPrev();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getNext())
            {
                ret[pMasqueradingVector[3]]=(Json::UInt64)getValueOfNext();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getCreated())
            {
                ret[pMasqueradingVector[4]]=getCreated()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getGameid())
    {
        ret["gameId"]=(Json::UInt64)getValueOfGameid();
    }
    else
    {
        ret["gameId"]=Json::Value();
    }
    if(getStateid())
    {
        ret["stateId"]=(Json::UInt64)getValueOfStateid();
    }
    else
    {
        ret["stateId"]=Json::Value();
    }
    if(getPrev())
    {
        ret["prev"]=(Json::UInt64)getValueOfPrev();
    }
    else
    {
        ret["prev"]=Json::Value();
    }
    if(getNext())
    {
        ret["next"]=(Json::UInt64)getValueOfNext();
    }
    else
    {
        ret["next"]=Json::Value();
    }
    if(getCreated())
    {
        ret["created"]=getCreated()->toDbStringLocal();
    }
    else
    {
        ret["created"]=Json::Value();
    }
    return ret;
}

bool History::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("gameId"))
    {
        if(!validJsonOfField(0, "gameId", pJson["gameId"], err, true))
            return false;
    }
    else
    {
        err="The gameId column cannot be null";
        return false;
    }
    if(pJson.isMember("stateId"))
    {
        if(!validJsonOfField(1, "stateId", pJson["stateId"], err, true))
            return false;
    }
    else
    {
        err="The stateId column cannot be null";
        return false;
    }
    if(pJson.isMember("prev"))
    {
        if(!validJsonOfField(2, "prev", pJson["prev"], err, true))
            return false;
    }
    if(pJson.isMember("next"))
    {
        if(!validJsonOfField(3, "next", pJson["next"], err, true))
            return false;
    }
    if(pJson.isMember("created"))
    {
        if(!validJsonOfField(4, "created", pJson["created"], err, true))
            return false;
    }
    return true;
}
bool History::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    if(!pMasqueradingVector[0].empty())
    {
        if(pJson.isMember(pMasqueradingVector[0]))
        {
            if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                return false;
        }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
    }
    if(!pMasqueradingVector[1].empty())
    {
        if(pJson.isMember(pMasqueradingVector[1]))
        {
            if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                return false;
        }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
    }
    if(!pMasqueradingVector[2].empty())
    {
        if(pJson.isMember(pMasqueradingVector[2]))
        {
            if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                return false;
        }
    }
    if(!pMasqueradingVector[3].empty())
    {
        if(pJson.isMember(pMasqueradingVector[3]))
        {
            if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                return false;
        }
    }
    if(!pMasqueradingVector[4].empty())
    {
        if(pJson.isMember(pMasqueradingVector[4]))
        {
            if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                return false;
        }
    }
    return true;
}
bool History::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("gameId"))
    {
        if(!validJsonOfField(0, "gameId", pJson["gameId"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("stateId"))
    {
        if(!validJsonOfField(1, "stateId", pJson["stateId"], err, false))
            return false;
    }
    if(pJson.isMember("prev"))
    {
        if(!validJsonOfField(2, "prev", pJson["prev"], err, false))
            return false;
    }
    if(pJson.isMember("next"))
    {
        if(!validJsonOfField(3, "next", pJson["next"], err, false))
            return false;
    }
    if(pJson.isMember("created"))
    {
        if(!validJsonOfField(4, "created", pJson["created"], err, false))
            return false;
    }
    return true;
}
bool History::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
            return false;
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
            return false;
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
            return false;
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
            return false;
    }
    return true;
}
bool History::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson, 
                               std::string &err, 
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;                
            }
            break;
     
        default:
            err="Internal error in the server";
            return false;
            break;
    }
    return true;
}
