/**
 *
 *  States.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

using namespace drogon::orm;
namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace sqlite3 
{

class States
{
  public:
    struct Cols
    {
        static const std::string _state_id;
        static const std::string _state;
        static const std::string _player;
        static const std::string _endgame_state;
        static const std::string _n_moves;
        static const std::string _white_captures;
        static const std::string _black_captures;
        static const std::string _board;
        static const std::string _created;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = uint64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names, 
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all 
     * columns by an asterisk), please set the offset to -1.
     */
    explicit States(const Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit States(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    States(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    States() = default;
    
    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson, 
                          std::string &err, 
                          bool isForCreation);

    /**  For column state_id  */
    ///Get the value of the column state_id, returns the default value if the column is null
    const uint64_t &getValueOfStateId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getStateId() const noexcept;

    ///Set the value of the column state_id
    void setStateId(const uint64_t &pStateId) noexcept;
    void setStateIdToNull() noexcept;


    /**  For column state  */
    ///Get the value of the column state, returns the default value if the column is null
    const std::string &getValueOfState() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getState() const noexcept;

    ///Set the value of the column state
    void setState(const std::string &pState) noexcept;
    void setState(std::string &&pState) noexcept;


    /**  For column player  */
    ///Get the value of the column player, returns the default value if the column is null
    const std::string &getValueOfPlayer() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPlayer() const noexcept;

    ///Set the value of the column player
    void setPlayer(const std::string &pPlayer) noexcept;
    void setPlayer(std::string &&pPlayer) noexcept;


    /**  For column endgame_state  */
    ///Get the value of the column endgame_state, returns the default value if the column is null
    const std::string &getValueOfEndgameState() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getEndgameState() const noexcept;

    ///Set the value of the column endgame_state
    void setEndgameState(const std::string &pEndgameState) noexcept;
    void setEndgameState(std::string &&pEndgameState) noexcept;


    /**  For column n_moves  */
    ///Get the value of the column n_moves, returns the default value if the column is null
    const uint64_t &getValueOfNMoves() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getNMoves() const noexcept;

    ///Set the value of the column n_moves
    void setNMoves(const uint64_t &pNMoves) noexcept;


    /**  For column white_captures  */
    ///Get the value of the column white_captures, returns the default value if the column is null
    const std::string &getValueOfWhiteCaptures() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getWhiteCaptures() const noexcept;

    ///Set the value of the column white_captures
    void setWhiteCaptures(const std::string &pWhiteCaptures) noexcept;
    void setWhiteCaptures(std::string &&pWhiteCaptures) noexcept;


    /**  For column black_captures  */
    ///Get the value of the column black_captures, returns the default value if the column is null
    const std::string &getValueOfBlackCaptures() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBlackCaptures() const noexcept;

    ///Set the value of the column black_captures
    void setBlackCaptures(const std::string &pBlackCaptures) noexcept;
    void setBlackCaptures(std::string &&pBlackCaptures) noexcept;


    /**  For column board  */
    ///Get the value of the column board, returns the default value if the column is null
    const std::string &getValueOfBoard() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBoard() const noexcept;

    ///Set the value of the column board
    void setBoard(const std::string &pBoard) noexcept;
    void setBoard(std::string &&pBoard) noexcept;


    /**  For column created  */
    ///Get the value of the column created, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreated() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreated() const noexcept;

    ///Set the value of the column created
    void setCreated(const ::trantor::Date &pCreated) noexcept;



    static size_t getColumnNumber() noexcept {  return 9;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend Mapper<States>;
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<uint64_t> stateId_;
    std::shared_ptr<std::string> state_;
    std::shared_ptr<std::string> player_;
    std::shared_ptr<std::string> endgameState_;
    std::shared_ptr<uint64_t> nMoves_;
    std::shared_ptr<std::string> whiteCaptures_;
    std::shared_ptr<std::string> blackCaptures_;
    std::shared_ptr<std::string> board_;
    std::shared_ptr<::trantor::Date> created_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[9]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where state_id = ?";
        return sql;                   
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where state_id = ?";
        return sql;                   
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "state_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "state,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "player,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "endgame_state,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "n_moves,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "white_captures,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "black_captures,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "board,";
            ++parametersCount;
        }
        sql += "created,";
        ++parametersCount;
        if(!dirtyFlag_[8])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";
        
        if(dirtyFlag_[0])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        } 
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        } 
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;   
    }
};
} // namespace sqlite3
} // namespace drogon_model
